CC=g++
CFLAGS=-Wall -std=c++11

all: Task1 Task2

Task1: lab01_Task1.cpp
	$(CC) $(CFLAGS) lab01_Task1.cpp -o Task1

Task2: lab01_Task2.cpp
	$(CC) $(CFLAGS) lab01_Task2.cpp -o Task2

clean:
	rm -f Task1 Task2